apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-disk01
  namespace: ai_chat
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - "172.16.0.1:2345"
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
